using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using TMPro;
using System.Collections.Generic;

public class MenuManager : MonoBehaviour
{
    private const string HighestUnlockedLevelKey = "highest_unlocked_level";

    [System.Serializable]
    public class LevelButtonEntry
    {
        public int levelNumber;
        public Button button;
    }

    [Header("Main Menu")]
    [SerializeField] private string levelsSceneName = "Levels";

    [Header("Level Pages")]
    [SerializeField] private string levelsPage1SceneName = "Levels";
    [SerializeField] private string levelsPage2SceneName = "Levels1";

    [Header("Prebuilt UI")]
    [SerializeField] private bool useAutoGeneratedButtons = false;
    [SerializeField] private List<LevelButtonEntry> prebuiltLevelButtons = new List<LevelButtonEntry>();

    [Header("Auto-Generated Level Menu")]
    [SerializeField] private Transform levelButtonContainer;
    [SerializeField] private Button levelButtonPrefab;
    [SerializeField] private int totalLevels = 40;

    [Header("Level Loading")]
    [SerializeField] private bool loadByBuildIndex = false;
    [SerializeField] private int firstLevelBuildIndex = 1;
    [SerializeField] private string levelScenePrefix = "Level";

    [Header("Optional Button Visuals")]
    [SerializeField] private string lockIconChildName = "Lock";

    private void Start()
    {
        if (useAutoGeneratedButtons)
        {
            BuildLevelButtons();
        }
        else
        {
            RefreshPrebuiltLevelButtons();
        }
    }

    public void LevelMenu()
    {
        SceneManager.LoadScene(levelsPage1SceneName);
    }

    public void OpenLevelsPage1()
    {
        SceneManager.LoadScene(levelsPage1SceneName);
    }

    public void OpenLevelsPage2()
    {
        SceneManager.LoadScene(levelsPage2SceneName);
    }

    public void BuildLevelButtons()
    {
        if (levelButtonContainer == null || levelButtonPrefab == null)
        {
            return;
        }

        for (int i = levelButtonContainer.childCount - 1; i >= 0; i--)
        {
            Destroy(levelButtonContainer.GetChild(i).gameObject);
        }

        int highestUnlockedLevel = GetHighestUnlockedLevel();

        for (int levelNumber = 1; levelNumber <= Mathf.Max(1, totalLevels); levelNumber++)
        {
            Button button = Instantiate(levelButtonPrefab, levelButtonContainer);
            bool isUnlocked = levelNumber <= highestUnlockedLevel;

            SetButtonLabel(button, levelNumber.ToString());
            SetLockIconVisible(button, !isUnlocked);
            button.interactable = isUnlocked;

            int capturedLevelNumber = levelNumber;
            button.onClick.AddListener(() => LoadLevel(capturedLevelNumber));
        }
    }

    public void LoadLevel(int levelNumber)
    {
        int highestUnlockedLevel = GetHighestUnlockedLevel();
        if (levelNumber > highestUnlockedLevel)
        {
            return;
        }

        if (loadByBuildIndex)
        {
            int buildIndex = firstLevelBuildIndex + (levelNumber - 1);
            if (buildIndex < 0 || buildIndex >= SceneManager.sceneCountInBuildSettings)
            {
                return;
            }

            SceneManager.LoadScene(buildIndex);
            return;
        }

        string sceneName = levelScenePrefix + levelNumber;
        SceneManager.LoadScene(sceneName);
    }

    public static int GetHighestUnlockedLevel()
    {
        return Mathf.Max(1, PlayerPrefs.GetInt(HighestUnlockedLevelKey, 1));
    }

    public static void MarkLevelComplete(int completedLevelNumber)
    {
        int currentHighest = GetHighestUnlockedLevel();
        int nextLevelToUnlock = Mathf.Max(1, completedLevelNumber + 1);

        if (nextLevelToUnlock > currentHighest)
        {
            PlayerPrefs.SetInt(HighestUnlockedLevelKey, nextLevelToUnlock);
            PlayerPrefs.Save();
        }
    }

    public void ResetLevelProgress()
    {
        PlayerPrefs.SetInt(HighestUnlockedLevelKey, 1);
        PlayerPrefs.Save();

        if (useAutoGeneratedButtons)
        {
            BuildLevelButtons();
        }

        RefreshPrebuiltLevelButtons();
    }

    public void UnlockAllLevels()
    {
        PlayerPrefs.SetInt(HighestUnlockedLevelKey, Mathf.Max(1, totalLevels));
        PlayerPrefs.Save();

        if (useAutoGeneratedButtons)
        {
            BuildLevelButtons();
        }

        RefreshPrebuiltLevelButtons();
    }

    public void RefreshPrebuiltLevelButtons()
    {
        int highestUnlockedLevel = GetHighestUnlockedLevel();

        for (int i = 0; i < prebuiltLevelButtons.Count; i++)
        {
            LevelButtonEntry entry = prebuiltLevelButtons[i];
            if (entry == null || entry.button == null)
            {
                continue;
            }

            bool isUnlocked = entry.levelNumber <= highestUnlockedLevel;
            entry.button.interactable = isUnlocked;
            SetLockIconVisible(entry.button, !isUnlocked);
        }
    }

    private void SetButtonLabel(Button button, string label)
    {
        TMP_Text tmpText = button.GetComponentInChildren<TMP_Text>(true);
        if (tmpText != null)
        {
            tmpText.text = label;
            return;
        }

        Text uiText = button.GetComponentInChildren<Text>(true);
        if (uiText != null)
        {
            uiText.text = label;
        }
    }

    private void SetLockIconVisible(Button button, bool visible)
    {
        if (string.IsNullOrWhiteSpace(lockIconChildName))
        {
            return;
        }

        Transform lockIcon = button.transform.Find(lockIconChildName);
        if (lockIcon != null)
        {
            lockIcon.gameObject.SetActive(visible);
        }
    }
}